Update ixpclient

diff --git a/bin/ixpclient b/bin/ixpclient
--- a/bin/ixpclient
+++ b/bin/ixpclient
@@ -1,38 +1,334 @@
 #!/bin/bash
-        clear
-        echo ""
-		echo -e "\e[32m      ,a8a,  ,ggg,          ,gg ,ggggggggggg,       ,gggg,                                                                    ";
-		echo -e "\e[32m     ,8\" \"8,dP\"\"\"Y8,      ,dP' dP\"\"\"88\"\"\"\"\"\"Y8,   ,88\"\"\"Y8b,                              I8                            ,dPYb,\e[1m"
-		echo -e "\e[32m     d8   8bYb,_  \"8b,   d8\"   Yb,  88      \`8b  d8\"     \`Y8                              I8                            IP'\`Yb\e[1m"
-		echo -e "\e[32m     88   88 \`\"\"    Y8,,8P'     \`\"  88      ,8P d8'   8b  d8                           88888888                         I8  8I\e[1m"
-		echo -e "\e[32m     88   88         Y88\"           88aaaad8P\" ,8I    \"Y88P'                              I8                            I8  8'\e[1m"
-		echo -e "\e[32m     Y8   8P        ,888b           88\"\"\"\"\"    I8'             ,ggggg,     ,ggg,,ggg,     I8     ,gggggg,    ,ggggg,    I8 dP \e[1m"
-		echo -e "\e[32m     \`8, ,8'       d8\" \"8b,         88         d8             dP\"  \"Y8ggg ,8\" \"8P\" \"8,    I8     dP\"\"\"\"8I   dP\"  \"Y8ggg I8dP  \e[1m"
-		echo -e "\e[32m8888  \"8,8\"      ,8P'    Y8,        88         Y8,           i8'    ,8I   I8   8I   8I   ,I8,   ,8'    8I  i8'    ,8I   I8P   \e[1m"
-		echo -e "\e[32m\`8b,  ,d8b,     d8\"       \"Yb,      88         \`Yba,,_____, ,d8,   ,d8'  ,dP   8I   Yb, ,d88b, ,dP     Y8,,d8,   ,d8'  ,d8b,_ \e[1m"
-		echo -e "\e[32m  \"Y88P\" \"Y8  ,8P'          \"Y8     88           \`\"Y8888888 P\"Y8888P\"    8P'   8I   \`Y888P\"\"Y888P      \`Y8P\"Y8888P\"    8P'\"Y88\e[1m"
-        echo -e "\e[0m"
-		
-		echo ":: IXPControl - Shell Interface ::"
-		echo ""
-		
-PS3='Please enter your choice: '
-options=("Add Network" "Add Prefix" "Remove Network" "Quit")
-select opt in "${options[@]}"
-do
-    case $opt in
-        "Add Network")
-            echo "Lets add that network!"
-            ;;
-        "Add Prefix")
-            echo "lets add some prefixes!"
-            ;;
-        "Remove Network")
-            echo "you chose choice $REPLY which is $opt"
-            ;;
-        "Quit")
-            break
-            ;;
-        *) echo "invalid option $REPLY";;
-    esac
+clear
+echo ""
+echo -e "\e[32m ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: \e[1m"
+echo -e "\e[32m '####:'##::::'##:'########:::'######:::'#######::'##::: ##:'########:'########:::'#######::'##::::::: \e[1m";
+echo -e "\e[32m . ##::. ##::'##:: ##.... ##:'##... ##:'##.... ##: ###:: ##:... ##..:: ##.... ##:'##.... ##: ##::::::: \e[1m"
+echo -e "\e[32m : ##:::. ##'##::: ##:::: ##: ##:::..:: ##:::: ##: ####: ##:::: ##:::: ##:::: ##: ##:::: ##: ##::::::: \e[1m"
+echo -e "\e[32m : ##::::. ###:::: ########:: ##::::::: ##:::: ##: ## ## ##:::: ##:::: ########:: ##:::: ##: ##::::::: \e[1m"
+echo -e "\e[32m : ##:::: ## ##::: ##.....::: ##::::::: ##:::: ##: ##. ####:::: ##:::: ##.. ##::: ##:::: ##: ##::::::: \e[1m"
+echo -e "\e[32m : ##::: ##:. ##:: ##:::::::: ##::: ##: ##:::: ##: ##:. ###:::: ##:::: ##::. ##:: ##:::: ##: ##::::::: \e[1m"
+echo -e "\e[32m '####: ##:::. ##: ##::::::::. ######::. #######:: ##::. ##:::: ##:::: ##:::. ##:. #######:: ########: \e[1m"
+echo -e "\e[32m ....::..:::::..::..::::::::::......::::.......:::..::::..:::::..:::::..:::::..:::.......:::........:: \e[1m"
+echo -e "\e[32m :::::::::::::::::::::::::::::::::::: https://www.ixpcontrol.com :::::::::::::::::::::::::::(v 0.1a):: \e[1m"
+echo -e "\e[0m"
+echo ":: IXPControl - Shell Interface ::"
+echo ""
+echo "Select an option:"
+echo "   1) Add new Peer/ASN"
+echo "   2) Remove Peer/ASN"
+echo "   3) Manual Refresh ALL IRR Filter Rules"
+echo "   4) Exit"
+read -p "Option: " option
+until [[ "$option" =~ ^[1-4]$ ]]; do
+        echo "$option: invalid selection."
+        read -p "Option: " option
 done
+case "$option" in
+        1)
+                read -p "Peer Name: (ie, IXPControl Ltd.)"  peerName
+                echo "Setting $peerName"
+                read -p "Peer ASN: (NUMBERS ONLY)"  peerASN
+                echo "Setting $peerASN"
+                        if ! [[ "$peerASN" =~ ^[0-9]+$ ]]
+                          then
+                               echo "Invalid ASN Provided, Please Use NUMBERS Only. - Exiting. Please Retry."
+                               exit
+                        fi
+                        echo "Select an option:"
+                        echo "   1) IPv4 ONLY"
+                        echo "   2) IPv6 ONLY"
+                        echo "   3) DUAL STACK"
+                        read -p "Option: " stackOption
+                        until [[ "$stackOption" =~ ^[1-3]$ ]]; do
+                                echo "$stackOption: invalid selection."
+                        read -p "Option: " stackOption
+                        done
+                        case "$stackOption" in
+
+                        1)
+                                read -p "Neighbor Address:  "  peer4Address
+                                echo "Setting $peer4Address"
+                                        if [[ ! -e /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN ]]; then
+                                          mkdir /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN
+                                        fi 
+
+cat >> /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN/peer.conf <<EOL
+protocol bgp PEER_AS$peerASN from ix_peer
+{
+	neighbor	as $peerASN;
+	neighbor	$peer4Address;
+	description	"$peerASN - $peerName";
+	import filter
+	{
+		bgp_local_pref = 100;
+		if net.len <= PREFIX_MIN && net ~ PREFIX_AS$peerASN then accept;
+		if net.len >= PREFIX_MAX then reject;
+		reject;
+	};
+
+	export filter
+	{
+		if ((0,0,$peerASN)) ~ bgp_large_community then reject;
+		if net.len > PREFIX_MIN then reject;
+		accept;
+	};
+}
+EOL
+			exit
+                        ;;
+						
+                        2)
+                                read -p "Neighbor Address:  "  peer6Address
+                                echo "Setting $peer4Address"
+                                        if [[ ! -e /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN ]]; then
+                                          mkdir /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN
+                                        fi 
+
+cat >> /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN/peer.conf <<EOL
+protocol bgp PEER_AS$peerASN from ix_peer
+{
+	neighbor	as $peerASN;
+	neighbor	$peer6Address;
+	description	"$peerASN - $peerName";
+	import filter
+	{
+		bgp_local_pref = 100;
+		if net.len <= PREFIX_MIN && net ~ PREFIX_AS$peerASN then accept;
+		if net.len >= PREFIX_MAX then reject;
+		reject;
+	};
+
+	export filter
+	{
+		if ((0,0,$peerASN)) ~ bgp_large_community then reject;
+		if net.len > PREFIX_MIN then reject;
+		accept;
+	};
+}
+EOL
+			exit
+                        ;;
+						
+                        3)
+                                read -p "IPv4 Neighbor Address:  "  peer4Address
+                                echo "Setting $peer4Address"
+								read -p "IPv6 Neighbor Address:  "  peer6Address
+                                echo "Setting $peer6Address"
+                                        if [[ ! -e /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN ]]; then
+                                          mkdir /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN
+                                        fi 
+                                        if [[ ! -e /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN ]]; then
+                                          mkdir /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN
+                                        fi 
+cat >> /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN/peer.conf <<EOL
+protocol bgp PEER_AS$peerASN from ix_peer
+{
+	neighbor	as $peerASN;
+	neighbor	$peer4Address;
+	description	"$peerASN - $peerName";
+	import filter
+	{
+		bgp_local_pref = 100;
+		if net.len <= PREFIX_MIN && net ~ PREFIX_AS$peerASN then accept;
+		if net.len >= PREFIX_MAX then reject;
+		reject;
+	};
+
+	export filter
+	{
+		if ((0,0,$peerASN)) ~ bgp_large_community then reject;
+		if net.len > PREFIX_MIN then reject;
+		accept;
+	};
+}
+EOL
+cat >> /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN/peer.conf <<EOL
+protocol bgp PEER_AS$peerASN from ix_peer
+{
+	neighbor	as $peerASN;
+	neighbor	$peer6Address;
+	description	"$peerASN - $peerName";
+	import filter
+	{
+		bgp_local_pref = 100;
+		if net.len <= PREFIX_MIN && net ~ PREFIX_AS$peerASN then accept;
+		if net.len >= PREFIX_MAX then reject;
+		reject;
+	};
+
+	export filter
+	{
+		if ((0,0,$peerASN)) ~ bgp_large_community then reject;
+		if net.len > PREFIX_MIN then reject;
+		accept;
+	};
+}
+EOL
+echo "Success: Created Configuration"
+read -p "Does Peer ASN have an AS-SET? (ie, AS-IXPCONTROL)  [Y/N]" -n 1 -r
+echo  ""
+if [[ $REPLY =~ ^[Yy]$ ]]
+then
+read -p "What is the AS-SET?:  "  peerASSET
+echo "Setting $peerASSET"
+if [[ ! -e /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN ]]; then
+    echo $peerASSET > /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN/AS-SET
+fi
+if [[ ! -e /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN ]]; then
+    echo $peerASSET > /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN/AS-SET
+fi
+fi
+echo "Creating Prefix List"
+if [[ ! -e /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN/AS-SET ]]; then
+	peerAS=$(cat /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN/AS-SET)
+    echo "IPv4 AS-SET has been found, Searching Prefixes IPv4 via AS-SET"
+docker exec bgpq4.rs bgpq4 -bl "define PREFIX_AS$peerASN" -S NTTCOM,RADB,RIPE,ALTDB,BELL,LEVEL3,RGNET,APNIC,JPIRR,ARIN,BBOI,TC,AFRINIC,ARIN-WHOIS,REGISTROBR $peerAS > /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN/prefix_v4.conf
+else
+echo "No IPv4 AS-SET has been found, Looking up IRR Prefixes by ASN"
+docker exec bgpq4.rs bgpq4 -bl "define PREFIX_AS$peerASN" -S NTTCOM,RADB,RIPE,ALTDB,BELL,LEVEL3,RGNET,APNIC,JPIRR,ARIN,BBOI,TC,AFRINIC,ARIN-WHOIS,REGISTROBR AS$peerASN > /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN/prefix_v4.conf
+fi
+if [[ ! -e /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN/AS-SET ]]; then
+        peerAS=$(cat /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN/AS-SET)
+    echo "IPv6 AS-SET has been found, Searching Prefixes IPv6 via AS-SET"
+docker exec bgpq4.rs bgpq4 -b6l "define PREFIX_AS$peerASN" -S NTTCOM,RADB,RIPE,ALTDB,BELL,LEVEL3,RGNET,APNIC,JPIRR,ARIN,BBOI,TC,AFRINIC,ARIN-WHOIS,REGISTROBR $peerAS > /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN/prefix_v6.conf
+else
+echo "No IPv6 AS-SET has been found, Looking up IRR Prefixes by ASN"
+docker exec bgpq4.rs bgpq4 -b6l "define PREFIX_AS$peerASN" -S NTTCOM,RADB,RIPE,ALTDB,BELL,LEVEL3,RGNET,APNIC,JPIRR,ARIN,BBOI,TC,AFRINIC,ARIN-WHOIS,REGISTROBR AS$peerASN > /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN/prefix_v6.conf
+fi
+echo "Completed IRR Lookup"
+echo "Prefix Lists Generated"
+cat /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN/prefix_v4.conf /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN/prefix_v6.conf 2>/dev/null
+echo ""
+echo ""
+if [[ ! -e /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN ]]; then
+echo "Reconfiguring Bird4"
+docker exec RouteServer birdc configure soft;
+fi
+if [[ ! -e /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN ]]; then
+echo "Reconfiguring Bird6"
+docker exec RouteServer bird6c configure soft;
+fi
+echo "Complete"
+echo ""
+			exit
+                        ;;
+                        esac
+                exit
+        ;;
+		2)
+			read -p "Peer ASN: (NUMBERS ONLY)"  peerASN
+                echo "Seaching For $peerASN"
+                        if ! [[ "$peerASN" =~ ^[0-9]+$ ]]
+                          then
+                               echo "Invalid ASN Provided, Please Use NUMBERS Only. - Exiting. Please Retry."
+                               exit
+                        fi
+						if [[ ! -e /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN ]]; then
+						echo "IPv4 Session Found"
+						fi
+						if [[ ! -e /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN ]]; then
+						echo "IPv6 Session Found"
+						fi
+                        echo "Remove $peerASN from:"
+                        echo "   1) IPv4 ONLY"
+                        echo "   2) IPv6 ONLY"
+                        echo "   3) DUAL STACK"
+                        read -p "Option: " stackOption
+                        until [[ "$stackOption" =~ ^[1-3]$ ]]; do
+                                echo "$stackOption: invalid selection."
+                        read -p "Option: " stackOption
+                        done
+                        case "$stackOption" in
+						
+						1)
+							mv /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN /opt/ixpcontrol/data/routeserver/DISABLED/v4/PEERS/$peerASN
+						if [[ ! -e /opt/ixpcontrol/data/routeserver/DISABLED/v4/PEERS/$peerASN ]]; then
+							echo "Reconfiguring Bird4"
+							docker exec RouteServer birdc configure soft;
+						fi
+						;;
+						2)
+							mv /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN /opt/ixpcontrol/data/routeserver/DISABLED/v6/PEERS/$peerASN
+						if [[ ! -e /opt/ixpcontrol/data/routeserver/DISABLED/v6/PEERS/$peerASN ]]; then
+							echo "Reconfiguring Bird6"
+							docker exec RouteServer bird6c configure soft;
+						fi
+						;;
+						3)
+							mv /opt/ixpcontrol/data/routeserver/v4/PEERS/$peerASN /opt/ixpcontrol/data/routeserver/DISABLED/v4/PEERS/$peerASN
+							mv /opt/ixpcontrol/data/routeserver/v6/PEERS/$peerASN /opt/ixpcontrol/data/routeserver/DISABLED/v6/PEERS/$peerASN
+						if [[ ! -e /opt/ixpcontrol/data/routeserver/DISABLED/v4/PEERS/$peerASN ]]; then
+							echo "Reconfiguring Bird4"
+							docker exec RouteServer birdc configure soft;
+						fi
+						if [[ ! -e /opt/ixpcontrol/data/routeserver/DISABLED/v6/PEERS/$peerASN ]]; then
+							echo "Reconfiguring Bird6"
+							docker exec RouteServer bird6c configure soft; 
+						fi
+						;;
+						
+						esac
+			
+				exit
+		;;
+		
+		
+		3)
+			echo "Fetching IRR Lists, This may take a while.."
+cd /etc/bird/routeserver/v4/PEERS;
+for v4ASN in *; do
+    if [ -d "$v4ASN" ]; then
+		echo "Found ASN: $v4ASN"
+		if [[ ! -e /opt/ixpcontrol/data/routeserver/v4/PEERS/$v4ASN/AS-SET ]]; then
+			peerAS=$(cat /opt/ixpcontrol/data/routeserver/v6/PEERS/$v4ASN/AS-SET)
+				echo "AS-SET Present for ASN: $v4ASN - AS-SET: $peerAS"
+			docker exec bgpq4.rs bgpq4 -bl "define PREFIX_AS$v4ASN" -S NTTCOM,RADB,RIPE,ALTDB,BELL,LEVEL3,RGNET,APNIC,JPIRR,ARIN,BBOI,TC,AFRINIC,ARIN-WHOIS,REGISTROBR $peerAS > /opt/ixpcontrol/data/routeserver/v4/PEERS/$v4ASN/prefix_v4.conf
+			echo "ASN: $v4ASN using $peerAS Complete"
+			echo "Prefix List"
+			cat /opt/ixpcontrol/data/routeserver/v4/PEERS/$v4ASN/prefix_v4.conf
+			sleep 2
+		else
+			echo "NO AS-SET Found for $v4ASN, Using ASN Only."
+			docker exec bgpq4.rs bgpq4 -bl "define PREFIX_AS$v4ASN" -S NTTCOM,RADB,RIPE,ALTDB,BELL,LEVEL3,RGNET,APNIC,JPIRR,ARIN,BBOI,TC,AFRINIC,ARIN-WHOIS,REGISTROBR AS$v4ASN > /opt/ixpcontrol/data/routeserver/v4/PEERS/$v4ASN/prefix_v4.conf
+			echo "ASN: $v4ASN using ASv4ASN Complete"
+			echo "Prefix List"
+			cat /opt/ixpcontrol/data/routeserver/v4/PEERS/$v4ASN/prefix_v4.conf
+			sleep 2
+		fi
+    fi
+done
+cd /etc/bird/routeserver/v6/PEERS;
+for v6ASN in *; do
+    if [ -d "$v6ASN" ]; then
+		echo "Found ASN: $v6ASN"
+		if [[ ! -e /opt/ixpcontrol/data/routeserver/v4/PEERS/$v6ASN/AS-SET ]]; then
+			peerAS=$(cat /opt/ixpcontrol/data/routeserver/v6/PEERS/$v6ASN/AS-SET)
+				echo "AS-SET Present for ASN: $v6ASN - AS-SET: $peerAS"
+			docker exec bgpq4.rs bgpq4 -bl "define PREFIX_AS$v6ASN" -S NTTCOM,RADB,RIPE,ALTDB,BELL,LEVEL3,RGNET,APNIC,JPIRR,ARIN,BBOI,TC,AFRINIC,ARIN-WHOIS,REGISTROBR $peerAS > /opt/ixpcontrol/data/routeserver/v6/PEERS/$v6ASN/prefix_v4.conf
+			echo "ASN: $v6ASN using $peerAS Complete"
+			echo "Prefix List"
+			cat /opt/ixpcontrol/data/routeserver/v4/PEERS/$v6ASN/prefix_v4.conf
+			sleep 2
+		else
+			echo "NO AS-SET Found for $v6ASN, Using ASN Only."
+			docker exec bgpq4.rs bgpq4 -bl "define PREFIX_AS$v6ASN" -S NTTCOM,RADB,RIPE,ALTDB,BELL,LEVEL3,RGNET,APNIC,JPIRR,ARIN,BBOI,TC,AFRINIC,ARIN-WHOIS,REGISTROBR AS$v6ASN > /opt/ixpcontrol/data/routeserver/v6/PEERS/$v6ASN/prefix_v4.conf
+			echo "ASN: $v6ASN using ASv4ASN Complete"
+			echo "Prefix List"
+			cat /opt/ixpcontrol/data/routeserver/v4/PEERS/$v6ASN/prefix_v4.conf
+			sleep 2
+		fi
+    fi
+done
+echo "IRR Prefix List Fetching.. Complete"	
+echo ""
+echo ""
+		exit
+		;;
+		
+		
+        4)
+
+	exit
+	;;
+esac
